apiVersion: batch/v1
kind: CronJob
metadata:
  name: video-processing-cronjob
spec:
  schedule: "0 1 * * *"  # Run at 1:00 AM Israel time
  timeZone: "Asia/Jerusalem"
  jobTemplate:
    spec:
      parallelism: 10
      completions: 10
      template:
        metadata:
          labels:
            app: video-processor
        spec:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                    - key: app
                      operator: In
                      values:
                      - video-processor
                  topologyKey: "kubernetes.io/hostname"
          restartPolicy: Never
          containers:
          - name: video-processor
            image: me-west1-docker.pkg.dev/python-code-running/videoconvertrep/video-processor:latest
            imagePullPolicy: IfNotPresent
            env:
            - name: BUCKET_NAME
              value: "main_il"
            - name: INPUT_PREFIX
              value: "video_conversion_workplace/input_directory/"
            - name: OUTPUT_PREFIX
              value: "video_conversion_workplace/output_directory/"
            - name: METADATA_PREFIX
              value: "video_conversion_workplace/metadata/"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/var/secrets/google/kubernetes-access-perm.json"
            volumeMounts:
            - name: gcp-credentials
              mountPath: "/var/secrets/google"
              readOnly: true
          volumes:
          - name: gcp-credentials
            secret:
              secretName: gcp-credentials